import { ReactQueryProvider, ReduxProvider, ToastProvider } from "@/providers";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { Suspense } from "react";
import { DefaultLayout, Loading } from "../components";
import './globals.css';
import NavigationProcess from "../components/layouts/NavigationProcess";

const poppins = Poppins({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Fast Commerce Application.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">
    <Head>
      <link
        rel="shortcut icon"
        href="/assets/images/favicon/favicon.ico"
        type="image/x-icon"
      />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin=""
      />
    </Head>
    <body className={poppins.className}>
      <ToastProvider>
        <ReduxProvider>
          <ReactQueryProvider>
            <NavigationProcess>
              <DefaultLayout>
                {children}
              </DefaultLayout>
            </NavigationProcess>
          </ReactQueryProvider>
        </ReduxProvider>
      </ToastProvider>
    </body>
  </html>
}
